config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /en|kh/ do
    get 'sports/index', as: 'sports'
    resources :sports, only: :show do
      resources :events
    end

    resources :games do
      resources :sport_submissions do
        get :game_submission, on: :member
      end
      resources :events do
        get :game_pdf, on: :collection
      end
    end

    root 'landings#home'
    devise_for :users, session: 'users/sessions'

    namespace :admin do
      resources :organizations, except: :show do
        resources :sport_submissions, except: [:new, :create, :destroy]
      end
      resources :games do
        resources :events
        resources :game_sport_categories, except: :show
      end
      resources :notifications, only: :index
      resources :people
      resources :passports do
        member do
          get :verify
          get :invalid
        end
      end
      resources :sport_categories do
        resources :levels
        resources :notifications, only: %i[new create]
      end

      resources :card_types
    end

    resources :competitions
    resources :events, only: %i[index show] do
      resources :teams
      put :join, on: :member
    end
    resources :users do
      get :disable, on: :member
    end
    resources :performers do
      get :team_member_card,      on: :collection
    end

    get '/people/:person_id/check_qr', to: 'public#check_availibilities', as: 'person_check_availibilities'
    resources :people do
      resources :passports
      # get :check_availibilities
      post :confirm
      get :team_member_card,      on: :collection
    end
    namespace :sport_representer do
      resources :events, except: %i[new create edit update destroy] do
        get :game_pdf, on: :collection
      end
      resources :people, only: [:index, :show]
      resources :organizations, only: :index
    end

    resources :scannings, only: :index
    resources :card_activations, only: :index do
      get :activate, on: :collection
    end
  end
  namespace :api do
    resources :sport_categories, only: [:search] do
      get :search, on: :collection
    end
    resources :people, only: %i[show find] do
      collection do
        get :find
      end
    end
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :game_sport_category_level

  has_many :teams, dependent: :nullify
  has_many :people, through: :teams

  STATE = %w(Open Close Start End)
  GENDER_REQUIRED = %w(both male female)

  validates :title, :open_registered_at, :close_registered_at, :started_at, :ended_at, :game_sport_category_level_id, presence: true
  # validates :game_sport_category_level, uniqueness: true
  validates :gender_required, inclusion: { in: GENDER_REQUIRED}

  delegate :level,                  to: :game_sport_category_level
  delegate :level_label,            to: :game_sport_category_level
  delegate :level_label_with_sport, to: :game_sport_category_level

  delegate :sport_name,     to: :game_sport_category_level, allow_nil: true
  delegate :sport_category, to: :game_sport_category_level
  delegate :game,           to: :game_sport_category_level

  delegate :number_of_player, to: :level
  delegate :competition_name, to: :level

  def state
    today = Date.today
    if open_registered_at < today
      if close_registered_at < today
        if started_at < today
          if ended_at < today
            return 'End'
          end
          return 'Start'
        end
        return 'Closed'
      end
      return 'Open'
    end
  end

  def self.current
    where('CURRENT_DATE BETWEEN started_at AND ended_at')
  end

  def self.started
    where('started_at <= CURRENT_DATE')
  end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < AdminBaseController
  before_action :find_game
  before_action :find_event, only: [:edit, :update, :show, :destroy]
  def index

  end

  def new
    @event = Event.new()
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to admin_game_path(@game)
      flash[:notice] = I18n.t('notify.success_save')
    else
      render :new
      flash[:notice] = I18n.t('notify.failed_save')
    end
  end

  def edit
  end

  def update
    if @event.update_attributes(event_params)
      redirect_to admin_game_path(@game)
      flash[:notice] = I18n.t('notify.success_save')
    else
      render :edit
      flash[:notice] = I18n.t('notify.failed_save')
    end
  end

  def show
    @team_grid = TeamGrid.new(){ |scope| scope = Team.where(event: @event) }
  end

  def destroy
    if @event.destroy
      redirect_to admin_game_path(@game)
      flash[:notice] = I18n.t('notify.success_delete')
    else
      redirect_to admin_game_path(@game)
      flash[:notice] = I18n.t('notify.failed_delete')
    end
  end

  private

  def find_game
    @game = Game.find(params[:game_id])
  end

  def find_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :age_from, :age_to, :gender_required, :weight_required, :started_at, :ended_at, :open_registered_at, :close_registered_at, :location, :description, :game_sport_category_level_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_game, only: [:index, :game_pdf]
  before_action :find_event, only: [:show, :join]
  def index
    game_sport_categories = GameSportCategory.where(sport_category_id: params[:sport_id], game: @game)

    @events = Event.joins(:game_sport_category_level).where(game_sport_category_levels: { game_sport_category_id: game_sport_categories.ids})
  end

  def show
    @team = Team.find_by(event: @event, user: current_user)
  end

  def game_pdf
    @game         = Game.current_active
    @sport        = SportCategory.find(params[:sport_id])
    @teams        = @game.teams.joins(:user).where( sport_category: @sport, users: {organization_id: current_user.organization.id})
    @non_athletes = Person.joins(:person_teams).non_athlete.where(person_teams: {team_id: @teams.ids} ).ordered_by_event_position

    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "Game_#{Time.now.strftime("%V-%b-%y-%H-%M-%S")}",
          template: 'events/game_pdf',
          orientation: 'Landscape',
          encoding: 'utf8',
          layout: 'layouts/pdf_layout.haml',
          margin: { top: 5, left: 3, right: 3 }
        end
      end
  end

  def join
    @team = Team.find(params[:team_id])
    event_team = @event.event_teams.new(team: @team)
    if event_team.save
      redirect_to event_path(@event)
      flash[:notice] = I18n.t('notify.success_save')
    else
      redirect_to event_path(@event)
      flash[:alert] = I18n.t('notify.failed_save')
    end
  end

  protected

  def find_event
    @event = Event.find(params[:id])
  end

  def set_game
    @game = Game.find(params[:game_id])
  end
end

app/controllers/sport_representer/events_controller.rb
module SportRepresenter
  class EventsController < ApplicationController
    # before_action :authorize_user
    def index
      authorize :sport_representer_event
      @game = Game.current_active
      game_sport_categories = GameSportCategory.where(sport_category: current_user.sport_category, game: @game)

      @events = Event.joins(:game_sport_category_level).where(game_sport_category_levels: { game_sport_category: game_sport_categories})
    end

    def game_pdf
      @game = Game.current_active
      @sport = current_user.sport_category
      @teams = @game.teams.where( sport_category: @sport)
      @non_athletes = Person.joins(:person_teams).non_athlete.where(person_teams: {team_id: @teams.ids} ).ordered_by_event_position
      game_sport_categories = GameSportCategory.where(sport_category: current_user.sport_category, game: @game)

      respond_to do |format|
        format.html
        format.pdf do
          render pdf: "Event_Game_#{Time.now.strftime("%V-%b-%y-%H-%M-%S")}",
            template: 'events/game_pdf',
            orientation: 'Landscape',
            encoding: 'utf8',
            layout: 'layouts/pdf_layout.haml',
            margin: { top: 5, left: 3, right: 3 }
          end
        end
    end

    def show
      authorize :sport_representer_event, :show?
      @event = Event.find(params[:id])
      @teams = Team.where(event: @event)
    end

    private

    def authorize_user
      authorize :sport_representer_event
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def event_state_label(state)
    case state
    when 'Open'
      klass = 'label label-info'
    when 'Close'
      klass = 'label label-warning'
    when 'Start'
      klass = 'label label-success'
    when 'End'
      klass = 'label label-danger'
    end
    content_tag(:span, state, class: klass)
  end
end

app/views/admin/events/_action.haml
.action-url.event{'data-path': game_event_path(event.game, event)}
  - if current_user.admin?
    = link_to edit_admin_game_event_path(event.game, event)do
      = fa_icon 'pencil', class: 'icon-border icon-info'
  -# = link_to person_path(person), method: :delete do
  -#   = fa_icon 'trash', method: :delete, class: 'icon-border'

app/views/admin/events/_form.haml
= simple_form_for([:admin, @game, @event]) do |f|
  .row
    .col-xs-2
      = f.label :game_sport_level, label: t('.game_sport_level')
    .col-xs-10
      = f.input :game_sport_category_level_id,
        collection: Game.find(@game).game_sport_category_levels.map{ |level| [level.level_label_with_sport, level.id] },
        label: false
  %br
  .row
    .col-xs-2
      = f.label :title, label: t('.title')
    .col-xs-10
      = f.input :title, label: false
  %br
  .row
    .col-xs-2
      = f.label :age, label: t('.age')
    .col-xs-5
      = f.label :from, label: t('.from')
      = f.input :age_from, label: false
    .col-xs-5
      = f.label :to, label: t('.to')
      = f.input :age_to, label: false

  %br
  .row
    .col-xs-2
      = f.label :gender_required, label: t('.gender_required')
    .col-xs-10
      = f.input :gender_required, collection: Event::GENDER_REQUIRED, input_html: { value: f.object.gender_required}, label: false, prompt: 'Select Gender Required'
  %br
  .row
    .col-xs-2
      = f.label :weight_required, label: t('.weight_required')
    .col-xs-10
      = f.input :weight_required, label: false
  %br
  .row
    .col-xs-2
      = f.label :started_at, label: t('.started_at')
    .col-xs-10
      = f.input :started_at, as: :string, input_html: { class: 'datepicker' }, label: false
  %br
  .row
    .col-xs-2
      = f.label :ended_at, label: t('.ended_at')
    .col-xs-10
      = f.input :ended_at, as: :string, input_html: { class: 'datepicker' }, label: false
  %br
  .row
    .col-xs-2
      = f.label :open_registered_at, label: t('.open_registered_at')
    .col-xs-10
      = f.input :open_registered_at, as: :string, input_html: { class: 'datepicker' }, label: false
  %br
  .row
    .col-xs-2
      = f.label :close_registered_at, label: t('.close_registered_at')
    .col-xs-10
      = f.input :close_registered_at, as: :string, input_html: { class: 'datepicker' }, label: false
  %br
  .row
    .col-xs-2
      = f.label :location, label: t('.location')
    .col-xs-10
      = f.input :location, label: false
  %br
  .row
    .col-xs-2
      = f.label :description, label: t('.description')
    .col-xs-10
      = f.input :description, label: false
      -# = f.input :sport_category_id, as: :hidden, input_html: { value: @sport.id }
  .row
    .col-xs-12.text-right
      = f.submit t('.save'), class: 'btn btn-success'

app/views/admin/events/edit.haml
.x_panel
  .x_title
    %h5= t('.event')
  .x_content
    = render 'form'

app/views/admin/events/new.haml
.x_panel
  .x_title
    %h5= t('.new_event')
  .x_content
    = render 'form'

app/views/admin/events/show.haml
.row
  .x_panel
    .x_title
      %h5 Event
    .x_content
      %h3.text-center
        %span= @event.title
        %span.label.label-info= @event.state
        
      .row
        .col-xs-12.col-md-6
          %table.table.table-bordered
            %tr
              %td
                Sport
              %td
                %b= @event.sport_category.name
            %tr
              %td
                Start Date
              %td
                %b= @event.started_at
            %tr
              %td
                End Date
              %td
                %b= @event.ended_at

            %tr
              %td
                Location
              %td
                %b= @event.location
            - if @event.description.present?
              %tr
                %td
                  Description
                %td
                  %b= @event.description

        .col-xs-12.col-md-6
          %table.table.table-bordered
            %tr
              %td
                Open Register Date
              %td
                %b= @event.open_registered_at
            %tr
              %td
                Close Register Date
              %td
                %b= @event.close_registered_at
      .ln_solid

      .row
        .col-xs-12
          = link_to 'Back', admin_sport_category_path(params[:sport_category_id]), class: 'btn btn-default'
.row
  .x_panel
    .x_title
      %h5 Teams
    .x_content
      .row
        .col-xs-12
          = datagrid_table @team_grid, html: {class: 'table table-condensed teams-table'}