config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /en|kh/ do
    get 'sports/index', as: 'sports'
    resources :sports, only: :show do
      resources :events
    end

    resources :games do
      resources :sport_submissions do
        get :game_submission, on: :member
      end
      resources :events do
        get :game_pdf, on: :collection
      end
    end

    root 'landings#home'
    devise_for :users, session: 'users/sessions'

    namespace :admin do
      resources :organizations, except: :show do
        resources :sport_submissions, except: [:new, :create, :destroy]
      end
      resources :games do
        resources :events
        resources :game_sport_categories, except: :show
      end
      resources :notifications, only: :index
      resources :people
      resources :passports do
        member do
          get :verify
          get :invalid
        end
      end
      resources :sport_categories do
        resources :levels
        resources :notifications, only: %i[new create]
      end

      resources :card_types
    end

    resources :competitions
    resources :events, only: %i[index show] do
      resources :teams
      put :join, on: :member
    end
    resources :users do
      get :disable, on: :member
    end
    resources :performers do
      get :team_member_card,      on: :collection
    end

    get '/people/:person_id/check_qr', to: 'public#check_availibilities', as: 'person_check_availibilities'
    resources :people do
      resources :passports
      # get :check_availibilities
      post :confirm
      get :team_member_card,      on: :collection
    end
    namespace :sport_representer do
      resources :events, except: %i[new create edit update destroy] do
        get :game_pdf, on: :collection
      end
      resources :people, only: [:index, :show]
      resources :organizations, only: :index
    end

    resources :scannings, only: :index
    resources :card_activations, only: :index do
      get :activate, on: :collection
    end
  end
  namespace :api do
    resources :sport_categories, only: [:search] do
      get :search, on: :collection
    end
    resources :people, only: %i[show find] do
      collection do
        get :find
      end
    end
  end
end

app/models/passport.rb
class Passport < ApplicationRecord
  belongs_to :person

  mount_uploader :passport_picture, PassportPictureUploader

  STATE = %w(Pending Verify Invalid Expired)

  delegate :name, to: :person
end

app/controllers/admin/passports_controller.rb
class Admin::PassportsController < AdminBaseController

  before_action :find_passport, only: [:show, :verify, :invalid]

  def index
    @passport_grid = PassportGrid.new(params[:passport_grid])
  end

  def show

  end

  def verify
    if @passport.update_attributes(state: 'Verify')
      redirect_to admin_passports_path
      flash[:notice] = I18n.t('notify.success_save')
    else
      redirect_to admin_passports_path
      flash[:notice] = I18n.t('notify.failed_save')
    end
  end

  def invalid
    if @passport.update_attributes(state: 'Invalid')
      redirect_to admin_passports_path
      flash[:notice] = I18n.t('notify.success_save')
    else
      redirect_to admin_passports_path
      flash[:notice] = I18n.t('notify.failed_save')
    end
  end

  private

  def find_passport
    @passport = Passport.find(params[:id])
  end
end

app/controllers/passports_controller.rb
class PassportsController < ApplicationController
  before_action :find_person
  before_action :find_passport, only: [:edit, :update, :destroy]

  def new
    @passport = Passport.new
  end

  def create
    @passport = Passport.new(passport_params)
    if @passport.save
      redirect_to person_path(@person)
      flash[:notice] = I18n.t('notify.success_save')
    else
      render :new
      flash[:notice] = I18n.t('notify.failed_save')
    end
  end

  def edit
  end

  def update
    if @passport.update_attributes(passport_params)
      redirect_to person_path(@person)
      flash[:notice] = I18n.t('notify.success_save')
    else
      render :edit
      flash[:notice] = I18n.t('notify.failed_save')
    end
  end

  private

  def find_person
    @person = Person.find(params[:person_id])
  end

  def find_passport
    @passport = Passport.find(params[:id])
  end

  def passport_params
    params.require(:passport).permit(:passport_picture, :passport_validity, :passport_number, :person_id)
  end
end

app/helpers/passports_helper.rb
module PassportsHelper
  def passport_label_color(state)
    case state
    when 'Pending'
      klass = 'label label-warning'
    when 'Verify'
      klass = 'label label-success'
    when 'Invalid'
      klass = 'label label-danger'
    when 'Expired'
      klass = 'label label-danger'
    else
      klass = 'label label-danger'
      state = 'No Passport'
    end
    content_tag(:span, state, class: klass)
  end
end

app/views/admin/passports/_action.haml
.action-url.passport{'data-path': person_path(passport.person)}
  -# - if passport.state == 'Pending'
  = link_to 'Verify', verify_admin_passport_path(passport), class: 'btn btn-success btn-xs'
  -# - if passport.state == 'Verify'
  = link_to 'Invalid', invalid_admin_passport_path(passport), class: 'btn btn-warning btn-xs'

app/views/admin/passports/index.haml
.row
  .x_panel
    .x_title
      %h5= t('.passport_filter')
    .x_content
      = datagrid_form_for @passport_grid, url: admin_passports_path()

.row
  .x_panel
    .x_title
      %h5= t('.passport_list')
    .x_content
      = datagrid_table @passport_grid, html: {class: 'table table-condensed passports-table'}

app/views/admin/passports/show.haml
.col-xs-12.col-md-6
  .x_panel
    .x_title
      %h5 Passport
    .x_content
      - if @passport.present?
        .x_content
          .row
            .col-xs-2
              Passport Picture
            .col-xs-10
              = link_to @passport.passport_picture.url, { target: '_blank' } do
                = image_tag @passport.passport_picture, width: 250
          .row
            .col-xs-2
              Passport Number
            .col-xs-10
              = @passport.passport_number

          .row
            .col-xs-2
              Passport Validity
            .col-xs-10
              = @passport.passport_validity

          .row
            .col-xs-2
              Status
            .col-xs-10
              = @passport.passport_state

          .ln_solid
          .row
            - if policy(:admin).edit?
              = link_to 'Edit', edit_person_passport_path(@passport.person, @passport), class: 'btn btn-info'
            -# = link_to 'Delete', person_path(@person, @person.passport), method: :delete, class: 'btn btn-danger'