config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /en|kh/ do
    get 'sports/index', as: 'sports'
    resources :sports, only: :show do
      resources :events
    end

    resources :games do
      resources :sport_submissions do
        get :game_submission, on: :member
      end
      resources :events do
        get :game_pdf, on: :collection
      end
    end

    root 'landings#home'
    devise_for :users, session: 'users/sessions'

    namespace :admin do
      resources :organizations, except: :show do
        resources :sport_submissions, except: [:new, :create, :destroy]
      end
      resources :games do
        resources :events
        resources :game_sport_categories, except: :show
      end
      resources :notifications, only: :index
      resources :people
      resources :passports do
        member do
          get :verify
          get :invalid
        end
      end
      resources :sport_categories do
        resources :levels
        resources :notifications, only: %i[new create]
      end

      resources :card_types
    end

    resources :competitions
    resources :events, only: %i[index show] do
      resources :teams
      put :join, on: :member
    end
    resources :users do
      get :disable, on: :member
    end
    resources :performers do
      get :team_member_card,      on: :collection
    end

    get '/people/:person_id/check_qr', to: 'public#check_availibilities', as: 'person_check_availibilities'
    resources :people do
      resources :passports
      # get :check_availibilities
      post :confirm
      get :team_member_card,      on: :collection
    end
    namespace :sport_representer do
      resources :events, except: %i[new create edit update destroy] do
        get :game_pdf, on: :collection
      end
      resources :people, only: [:index, :show]
      resources :organizations, only: :index
    end

    resources :scannings, only: :index
    resources :card_activations, only: :index do
      get :activate, on: :collection
    end
  end
  namespace :api do
    resources :sport_categories, only: [:search] do
      get :search, on: :collection
    end
    resources :people, only: %i[show find] do
      collection do
        get :find
      end
    end
  end
end

app/models/game.rb
class Game < ApplicationRecord
  mount_uploader :logo, LogoUploader

  has_many :game_sport_categories, inverse_of: :game, dependent: :restrict_with_error
  has_many :sport_submissions,                        dependent: :restrict_with_error
  has_many :card_activations,                         dependent: :destroy

  has_many :levels,                     through: :game_sport_categories
  has_many :sport_categories,           through: :game_sport_categories
  has_many :game_sport_category_levels, through: :game_sport_categories
  has_many :events,                     through: :game_sport_category_levels
  has_many :teams,                      through: :events
  has_many :person_teams,               through: :teams
  has_many :people,                     through: :person_teams

  accepts_nested_attributes_for :sport_submissions, reject_if: :all_blank, allow_destroy: true

  validates :name, :year, :batch, presence: true

  # accepts_nested_attributes_for :game_sport_categories, reject_if: :all_blank, allow_destroy: true
  # accepts_nested_attributes_for :game_sport_category_levels

  def self.current_active
    last
  end
end

app/controllers/admin/games_controller.rb
class Admin::GamesController < AdminBaseController
  before_action :set_game, only: %i[show edit update destroy]

  def index
    @game_grid = GameGrid.new(params[:game_grid])
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    if @game.save
      redirect_to admin_game_path(@game)
      flash[:notice] = I18n.t('notify.success_save')
    else
      render :new
      flash[:notice] = I18n.t('notify.failed_save')
    end
  end

  def edit; end

  def show
    @people_grid = PersonTeamGrid.new(params.fetch(:person_team_grid, {}).merge(current_user: current_user)) do |scope|
      scope.joins(:person_teams).distinct.where(person_teams: { id: @game.person_teams.ids }).where(id: @game.people).select('people.*, person_teams.position').page(params[:page])
    end
  end

  def update
    if @game.update_attributes(game_params)
      redirect_to admin_game_path(@game)
      flash[:notice] = I18n.t('notify.success_save')
    else
      render :edit
      flash[:notice] = I18n.t('notify.failed_save')
    end
  end

  def destroy
    if @game.destroy
      redirect_to admin_games_path
      flash[:notice] = I18n.t('notify.success_delete')
    else
      redirect_to admin_games_path
      flash[:notice] = I18n.t('notify.failed_delete')
    end
  end

  private

  def game_params
    params.require(:game).permit(:name, :year, :batch, :logo)
  end

  def set_game
    @game = Game.find(params[:id])
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/admin/games/_action.haml
.action-url.game{'data-path': admin_game_path(game)}
  - if policy(:admin).edit?
    = link_to edit_admin_game_path(game), class: 'btn btn-success btn-xs' do
      = fa_icon 'pencil'
  - if policy(:admin).destroy?
    = link_to admin_game_path(game), method: :delete, 'data-confirm': 'Are you sure?', class: 'btn btn-warning btn-xs' do
      = fa_icon 'trash'

app/views/admin/games/_form.haml
= simple_form_for([:admin, @game]) do |f|
  .row
    .col-xs-12
      #logo
        .row
          .col-xs-12
            = image_tag f.object.logo, class: 'image_to_upload logo-thumb', width: 120
          .col-xs-12
            = f.file_field :logo, class: 'photo_upload'
  %br
  .row
    .col-xs-12
      = f.input :name, label: t('.name')
  %br
  .row
    .col-xs-6
      = f.input :batch, label: t('.batch')
    .col-xs-6
      = f.input :year, label: t('.year')
  %br
  .row
    .col-xs-12.text-right
      = f.submit t('.save') , class: 'btn btn-success'

app/views/admin/games/_game_sport_category_fields.haml
-# .nested-fields.row
-#   .col-xs-12.col-sm-6
-#     = f.input :sport_category_id,
-#       label: false,
-#       collection: SportCategory.pluck(:name, :id),
-#       input_html: { class: 'select2 select-sport' }
-#   .col-xs-12.col-sm-3
-#     = link_to_remove_association f, class: 'btn btn-danger' do
-#       = fa_icon 'trash'

app/views/admin/games/edit.haml
.x_panel
  .x_title
    %h5 Edit Game
  .x_content
    = render 'form'

app/views/admin/games/index.haml
.row
  .col-xs-12.text-right
    - if policy(:admin).new?
      = link_to new_admin_game_path(), class: 'btn btn-primary btn-margin' do
        = t('.new_game')

.row
  .x_panel
    .x_title
      %h5= t('.game_list')
    .x_content
      = datagrid_table @game_grid, html: {class: 'table table-condensed games-table'}

app/views/admin/games/new.haml
.x_panel
  .x_title
    %h5= t('.new_game')
  .x_content
    = render 'form'

app/views/admin/games/show.haml
.row
  .col-xs-12
    .x_panel
      .x_title
        %h5= @game.name
      .x_content
        .row
          .col-xs-12
            %p Dashboard
        .row
          .col-xs-2
            Game:
          .col-xs-10
            = @game.name
        .row
          .col-xs-2
            = "#{t('.year')}:"
          .col-xs-4
            = @game.year
          .col-xs-2
            = "#{t('.batch')}:"
          .col-xs-4
            = @game.batch

  .col-xs-12
    .x_panel
      .x_title
        Filter People in Game
      .x_content
        = datagrid_form_for (@people_grid), url: admin_game_path(@game)
        .ln_solid
        = datagrid_table @people_grid, html: {class: 'table table-condensed people-table'}
      .text-center
        = will_paginate @people_grid.assets, renderer: BootstrapPagination::Rails

  .col-xs-12.col-sm-6
    .col-xs-12.text-right
      = link_to t('.new_game_event'), new_admin_game_game_sport_category_path(@game), class: 'btn btn-primary'
    .col-xs-12
      .x_panel
        .x_title
          %h5= t('.game_and_level')
        .x_content
          %table.table
            %thead
              %tr
                %th= t('.sport')
                %th= t('.level')
                %th
            %tbody
              - @game.game_sport_categories.each do |game_sport_category|
                %tr
                  %td= game_sport_category.sport_name
                  %td= game_sport_category.levels.map(&:level_label).join(', ')
                  %td{ style: "width: 75px;" }
                    = link_to edit_admin_game_game_sport_category_path(@game, game_sport_category) do
                      = fa_icon 'pencil', class: 'icon-border icon-info'
                    = link_to admin_game_game_sport_category_path(@game, game_sport_category), method: :delete, 'data-confirm': 'Are you sure?' do
                      = fa_icon 'trash', class: 'icon-border icon-danger'
  .col-xs-12.col-sm-6
    .col-xs-12.text-right
      = link_to t('.new_event'), new_admin_game_event_path(game_id: @game.id), class: 'btn btn-primary'
    .col-xs-12
      .x_panel
        .x_title
          %h5= t('.event')
        .x_content
          %table.table
            %thead
              %tr
                %th#event-table-header= t('.title')
                %th= t('.event_level')
                %th
            %tbody
              - @game.events.each do |event|
                %tr
                  %td= event.title
                  %td= event.level_label_with_sport
                  %td{ style: "width: 75px;" }
                    = link_to edit_admin_game_event_path(@game, event) do
                      = fa_icon 'pencil', class: 'icon-border icon-info'
                    = link_to admin_game_event_path(@game, event), method: :delete, 'data-confirm': 'Are you sure?' do
                      = fa_icon 'trash', class: 'icon-border icon-danger'