config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /en|kh/ do
    get 'sports/index', as: 'sports'
    resources :sports, only: :show do
      resources :events
    end

    resources :games do
      resources :sport_submissions do
        get :game_submission, on: :member
      end
      resources :events do
        get :game_pdf, on: :collection
      end
    end

    root 'landings#home'
    devise_for :users, session: 'users/sessions'

    namespace :admin do
      resources :organizations, except: :show do
        resources :sport_submissions, except: [:new, :create, :destroy]
      end
      resources :games do
        resources :events
        resources :game_sport_categories, except: :show
      end
      resources :notifications, only: :index
      resources :people
      resources :passports do
        member do
          get :verify
          get :invalid
        end
      end
      resources :sport_categories do
        resources :levels
        resources :notifications, only: %i[new create]
      end

      resources :card_types
    end

    resources :competitions
    resources :events, only: %i[index show] do
      resources :teams
      put :join, on: :member
    end
    resources :users do
      get :disable, on: :member
    end
    resources :performers do
      get :team_member_card,      on: :collection
    end

    get '/people/:person_id/check_qr', to: 'public#check_availibilities', as: 'person_check_availibilities'
    resources :people do
      resources :passports
      # get :check_availibilities
      post :confirm
      get :team_member_card,      on: :collection
    end
    namespace :sport_representer do
      resources :events, except: %i[new create edit update destroy] do
        get :game_pdf, on: :collection
      end
      resources :people, only: [:index, :show]
      resources :organizations, only: :index
    end

    resources :scannings, only: :index
    resources :card_activations, only: :index do
      get :activate, on: :collection
    end
  end
  namespace :api do
    resources :sport_categories, only: [:search] do
      get :search, on: :collection
    end
    resources :people, only: %i[show find] do
      collection do
        get :find
      end
    end
  end
end

app/models/organization.rb
class Organization < ApplicationRecord
  mount_uploader :logo, LogoUploader

  has_many :users
  has_many :sport_submissions
  has_many :people

  scope :non_admin, -> { where.not(name: 'Admin Team') }

  validates :org_label, :name, :short_code, presence: true

  scope :only_organization_reprenter, -> { joins(:users).where('users.role = ?', 'representer').uniq }

  def get_sport_submission
    sport_submissions.last
  end
end

app/controllers/admin/organizations_controller.rb
class Admin::OrganizationsController < AdminBaseController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  def index
    @organizations_grid = OrganizationsGrid.new(params[:organizations_grid]) do |scope|
      scope.page(params[:page])
    end
  end

  def new
    @organization = Organization.new
  end

  def edit
  end

  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to admin_organizations_url }
        flash[:notice] = I18n.t('notify.success_save')
      else
        format.html { render :new }
        flash[:notice] = I18n.t('notify.failed_save')
      end
    end
  end

  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to  admin_organizations_url}
        flash[:notice] = I18n.t('notify.success_save')
      else
        format.html { render :edit }
        flash[:notice] = I18n.t('notify.failed_save')
      end
    end
  end

  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to admin_organizations_url }
      flash[:notice] = I18n.t('notify.success_delete')
      format.json { head :no_content }
    end
  end

  private

  def set_organization
    @organization = Organization.find(params[:id])
  end

  def organization_params
    params.require(:organization).permit(:org_label, :name, :short_code, :logo)
  end
end

app/controllers/sport_representer/organizations_controller.rb
module SportRepresenter
  class OrganizationsController < ApplicationController
    def index
      authorize :sport_representer_organization
      sport_ids = []
      sport_ids << current_user.sport_category.id
      sport_ids << SportCategory.only_children.where(parent: current_user.sport_category).ids
      sport_ids.flatten!
      @organizations_grid = SportRepresenterOrganizationGrid.new(params[:sport_representer_organizations_grid]) do |scope|
        scope.joins(sport_submissions: :submission_sport_lists).where(sport_submissions: { submission_sport_lists: { sport_category: sport_ids} }).page(params[:page])
      end

      respond_to do |format|
        format.html
        format.xlsx {
          send_data(@organizations_grid.to_spreadsheet(sport_ids), type: 'application/xlsx', filename: "របាយការណ៍ចុះឈ្មោះ-#{Time.now.strftime("%V-%b-%y-%H-%M-%S")}.xlsx")
        }
      end
    end
  end
end

app/helpers/admin/organizations_helper.rb
module Admin::OrganizationsHelper
end

app/views/admin/organizations/_action.haml
- if policy(:admin).edit?
  = link_to I18n.t('actions.edit'), edit_admin_organization_path(model), class: 'btn btn-success btn-xs'
  - if model.sport_submissions.any?
    = link_to I18n.t('admin.organizations.index.edit_sport_submission'), edit_admin_organization_sport_submission_path(model, model.get_sport_submission), class: 'btn btn-warning btn-xs'
  - else
    = link_to I18n.t('admin.organizations.index.edit_sport_submission'), '#', class: 'btn btn-warning btn-xs', disabled: true

app/views/admin/organizations/_form.haml
= simple_form_for([:admin, organization]) do |f|
  = f.error_notification
  .form-inputs
    .row
      .col-xs-12
        = image_tag f.object.logo, class: 'image_to_upload logo-thumb', width: 120
      .col-xs-12
        = f.file_field :logo, class: 'photo_upload'
    %br/
    .row
      .col-xs-12.col-md-4
        = f.input :short_code, label: t('.short_code')
      .col-xs-12.col-md-4
        = f.input :name, label: t('.name')
      .col-xs-12.col-md-4
        = f.input :org_label, label: t('.org_label')
    .form-actions
      = f.submit t('actions.save'), class: 'btn btn-primary'

app/views/admin/organizations/edit.haml
.row
  .x_panel
    .x_title
      %h5= t('.edit_organization')
    .x_content
      = render 'form', organization: @organization

app/views/admin/organizations/index.haml
#notice= notice
.row
  .x_panel
    .x_title
      %h5= t('.organizations_filter')
    .x_content
      = datagrid_form_for @organizations_grid, :method => :get, :url => admin_organizations_path

.row
  .x_panel
    .x_title
      %h5= t('.organizations_list')
      - if policy(:admin).new?
        = link_to t('.add_organization'), new_admin_organization_path, class: 'btn btn-primary text-right', id: 'link-add-organization'
    .x_content
      = datagrid_table @organizations_grid, html: {class: 'table table-condensed organizations-table'}, unclickable: true
      = paginate(@organizations_grid.assets)

app/views/admin/organizations/new.haml
.row
  .x_panel
    .x_title
      %h5= t('.new_organization')
    .x_content
      = render 'form', organization: @organization

app/views/admin/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_organization_path(@organization) %> |
<%= link_to 'Back', admin_organizations_path %>